### ISSUE TITLE
実はエラーが出てない現状

### ISSUE THREAD

**Issue by sakamotomitsu** [rtsubaki00/Internship#3]
昨日のエラーの原因分かりました

question6.phpの下部にそのままコピペした文が
出てきているだけでした
それを消したら正常に動いたので大丈夫です

後、question6.phpのページ内に「登録する」というボタンがあります
question6.php内で、インサートをするSQL文を実行したらダメな気がします・・・・
question7.phpでインサートをするSQL文を実行しましょう

**Comment by sakamotomitsu** [comment]
@rtsubaki00 
修正が終わったら、クローズにしといてください！

余談ですが、コミット時のメッセージに
#3 をつけると、このissueに関連付けられたコミットとして認識されますよ！

**Comment by rtsubaki00** [comment]
修正終わりました！

#3機能いいですね！初めて知りました！

**Comment by sakamotomitsu** [comment]
@rtsubaki00 
![image](https://user-images.githubusercontent.com/38453886/85843525-3e0dc780-b7dc-11ea-9803-14a253f338f9.png)
画像の中の「＃」の所と連動してます！

issueに対して修正をしたものを関連付けて、
どのコミットで修正したのかを分かりやすくします！
